### ISSUE TITLE
Update the Plugins chapter

### ISSUE THREAD

**Issue by DenisVuyka** [DenisVuyka/developing-with-angular#37]
- explain that NgModule can contain multiple imports (Material components, other modules and providers)
- more examples on plugins injecting Angular entities (services, FormBuilder)
- clarify the Rollup is one of many options, i.e. it is possible to use ng-packagr as well

**Comment by Brandejs** [comment]
Hi, I recently discovered your book and I love it! I'm trying to create a plugin system in angular but I have a problem with DI. If my component needs a service like "HttpClient". I can not get it. Or if I Use @Extension decorator on NgModule I can resolve it and create module at runtime, but DI didn't solve dependencies. Can you please provide some hint how to solve that?

**Comment by DenisVuyka** [comment]
I suggest taking a look at this thread that gives some details on how to deal with dependencies: https://medium.com/@jean.marc.royy/hello-denys-thank-you-very-much-for-this-new-amazing-chapter-on-external-plugins-that-have-solved-7afadb940f63

**Comment by Brandejs** [comment]
Thanks. That really helped me.
Do you also have any experience with including _ngrx_ in a plugin? It looks like it's needed, some additional configuration.

https://pastebin.com/R6uMk2i1
`Error: Error: StaticInjectorError(AppModule)[StoreFeatureModule -> ReducerManager]: 
  StaticInjectorError(Platform: core)[StoreFeatureModule -> ReducerManager]: 
    NullInjectorError: No provider for ReducerManager!`
